### ISSUE TITLE
Add option to allow mod on server permanently

### ISSUE THREAD

**Issue by MasonGulu** [tr7zw/ItemSwapper#137]
### Is your feature request related to a problem?

I am playing on a public modded MC server, and have been given explicit permission to use client mods such as this. I don't do building a lot, so it ends up being awhile before I press r. When I do I'm not really expecting the popup taking me out of playing the game.

### Describe the solution you'd like

Adding a "remember this" option when selecting to enable the mod on the server.

### Describe alternatives you've considered

A whitelist file would work as well.

**Comment by tr7zw** [comment]
Duplicate #108

**Comment by MasonGulu** [comment]
So when will the mod be updated to add that? I'm running v0.3.2-1.19.3, the latest version available. Which I realize was released before that PR (after recording the video).

https://user-images.githubusercontent.com/70228812/221428556-e3c202a2-0af5-42b3-913b-7997fb8217f9.mp4

**Comment by tr7zw** [comment]
It will take more time since the update is rather big. You can download the current dev build from the actions tab. Also, that feature still needs to be reworked, because currently, it closes the message "too well"(no option to revoke it/see that the server does in fact still not support the mod). Also, since it's a modded server and the owners gave the ok, why throw it onto the server side, so the massage is gone in general(and shulkers working)?

**Comment by MasonGulu** [comment]
Because this is a large public server with a curated and custom mod list. They would not add a clientside mod to the server and force everyone to use it.

**Comment by tr7zw** [comment]
Serverside it just sends a few packets to clients to enable the feature. if the client is missing the mod, nothing happens. It behaves like the Spigot plugin.
