### ISSUE TITLE
Don't Swap Tools when picking Item

### ISSUE THREAD

**Issue by KrisTC** [tr7zw/ItemSwapper#188]
### Is your feature request related to a problem?

I think this came in v0.5.2-1.20 with the support for pulling from Shulkers, which is very exciting. 
But I only discovered this was working by accident, because I kept losing my pickaxe.
I have discovered that what is going on is I am using block pic on something I don't have in my inventory and my pickaxe ends up swapped into a shulker.
My feature request would be that tools or other non-blocks aren't swapped. The swap should find a slot with a block in it or ideally an empty slot.

### Describe the solution you'd like

My feature request would be that tools or other non-blocks aren't swapped. The swap should find a slot with a block in it or ideally an empty slot.
I don't mind if this is an option. Or if it is easier, to protect specific slots with a simple setting for which slots to protect.

**Comment by tr7zw** [comment]
Uhhhhh few issues:
Swapping always happens with the currently selected slot. So the fix is to just not pick block while holding a tool, as even in vanilla that will throw the tool into the inventory.
Also, there is no logic to do a "3-way swap" or mod-caused slot switches, and for now, that's also not planned.

**Comment by Malachi-lewis** [comment]
I don't think this is really a problem with standard swapping, but when you pick-block, it is annoying that this can happen when vanilla pick-blocking avoids diamond and netherite tools.
