### ISSUE TITLE
Vignette around menu when not in daylight and Optifabric installed

### ISSUE THREAD

**Issue by VitBudina** [tr7zw/ItemSwapper#23]
An odd vignette effect is shown around the item swapper menu when the player is not in daylight. The only way to get rid of this effect is to set the "Vignette" setting (Options>Video Settings>Details>Vignette) to "Fast". This issue seems to stem from Optifabric, as that is the mod that allows the player to change the Vignette settings. After removing Optifabric from the mods folder, the issue went away. Although I have other mods installed, I didn't find any that could possibly cause this issue. With that said, I will still include a list of the mods I use as I could've missed something.
Mods list:
AppleSkin
Better F3
Dynamic Surroundings: Remastered
Eating Animation
Effective
FerriteCore
Inventory HUD+
ItemSwapper
Litematica
MaLiLib
Mod Menu
Shulker Box Tooltip
Sound Physics Remastered
Starlight
WorldEdit

![image](https://user-images.githubusercontent.com/119748800/205450543-a1843ffe-4f44-4823-826a-4132abd1a469.png)
With Vignette: Default/Fancy

![image](https://user-images.githubusercontent.com/119748800/205450582-a4dee3a6-165c-4b80-b2c3-ddef1e1de003.png)
With Vignette: Fast

![image](https://user-images.githubusercontent.com/119748800/205450632-4d93a8fb-dfbe-4164-b01b-9279a53be909.png)
With Vignette: Default/Fancy in daylight (when transferring from no daylight to daylight, the vignette effect slowly dissipates, after roughly 20-30 seconds, the vignette effect disappears completely).

**Comment by tr7zw** [comment]
Yea noticed that too. For now the solution is to use Sodium instead.

**Comment by Bloemist** [comment]
Optifine freezes the screen during the use of ItemSwapper, due to this their internal "vignette" effect which keeps going on gets drawn over itself again and again, exaggerating the effect hugely. 

Disabling optifine's vignette effect in the video settings prevents this tunnel effect, but the gameplay screen will still be frozen while using ItemSwapper. 

Changing to optifine alternatives (a combination of sodium and other plugins) fixes this and has proven (for me at least) to be the better choice (way better performance, less buggy overall).

**Comment by VitBudina** [comment]
I found that too. The only reason I still use Optifine in place of Sodium is that I and my friend are working on builds with large glass pane surfaces at the moment, and although there are Sodium alternatives to connected glass textures, they are still buggy, especially with glass panes. Otherwise, I would've switched to Sodium long ago.

**Comment by tr7zw** [comment]
Should be fixed.
